{{- if .Values.core.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: harbor-core-policy
  namespace: harbor
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: core  # Targets Harbor Core Pods
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: jobservice  # Allow JobService
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: portal      # Allow Portal (UI)
      ports:
        - protocol: TCP
          port: 8080  # Core's default port
{{- end }}
