apiVersion: v1
kind: Service
metadata:
  name: harbor
  namespace: harbor
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  labels:
    app: harbor
    app.kubernetes.io/name: harbor
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 2.12.2
    app.kubernetes.io/part-of: harbor
    chart: harbor
    heritage: Helm
    release: harbor
spec:
  type: LoadBalancer
  selector:
    app: harbor
    component: nginx
    release: harbor
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
