{{- if .Values.portal.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: harbor-portal-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: portal
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: portal
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}   # allow all ingress
  egress:
    - {}   # allow all egress
{{- end }}
