apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "harbor.registry" . }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
    component: registry
    app.kubernetes.io/component: registry
spec:
  replicas: {{ .Values.registry.replicas }}
  revisionHistoryLimit: {{ .Values.registry.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if eq .Values.updateStrategy.type "Recreate" }}
    rollingUpdate: null
    {{- end }}
  selector:
    matchLabels:
      {{- include "harbor.matchLabels" . | nindent 6 }}
      component: registry
  template:
    metadata:
      labels:
        {{- include "harbor.labels" . | nindent 8 }}
        component: registry
        app.kubernetes.io/component: registry
      {{- if .Values.registry.podLabels }}
        {{- toYaml .Values.registry.podLabels | nindent 8 }}
      {{- end }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/registry/registry-cm.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/registry/registry-secret.yaml") . | sha256sum }}
        checksum/secret-jobservice: {{ include (print $.Template.BasePath "/jobservice/jobservice-secrets.yaml") . | sha256sum }}
        checksum/secret-core: {{ include (print $.Template.BasePath "/core/core-secret.yaml") . | sha256sum }}
        {{- if and .Values.internalTLS.enabled (eq .Values.internalTLS.certSource "auto") }}
        checksum/tls: {{ include (print $.Template.BasePath "/internal/auto-tls.yaml") . | sha256sum }}
        {{- else if and .Values.internalTLS.enabled (eq .Values.internalTLS.certSource "manual") }}
        checksum/tls: {{ include (print $.Template.BasePath "/registry/registry-tls.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.registry.podAnnotations }}
        {{- toYaml .Values.registry.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
        fsGroupChangePolicy: OnRootMismatch
      {{- if .Values.registry.serviceAccountName }}
      serviceAccountName: {{ .Values.registry.serviceAccountName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.registry.automountServiceAccountToken | default false }}
      terminationGracePeriodSeconds: 120
      {{- with .Values.registry.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range . }}
        - {{ . | toYaml | nindent 10 | trim }}
          labelSelector:
            matchLabels:
              {{- include "harbor.matchLabels" $ | nindent 14 }}
              component: registry
        {{- end }}
      {{- end }}
      initContainers:
      - name: fix-permissions
        image: busybox:1.35
        command: ['sh', '-c', 'chown -R 10000:10000 /storage']
        volumeMounts:
        - name: registry-data
          mountPath: /storage
          subPath: {{ .Values.persistence.persistentVolumeClaim.registry.subPath }}
        securityContext:
          runAsUser: 0
      containers:
      - name: registry
        image: {{ .Values.registry.registry.image.repository }}:{{ .Values.registry.registry.image.tag }}
        imagePullPolicy: {{ .Values.registry.registry.image.pullPolicy | default "Always" }}
        livenessProbe:
          httpGet:
            path: /
            scheme: {{ include "harbor.component.scheme" . | upper }}
            port: {{ template "harbor.registry.containerPort" . }}
          initialDelaySeconds: 300
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            scheme: {{ include "harbor.component.scheme" . | upper }}
            port: {{ template "harbor.registry.containerPort" . }}
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        resources:
          {{- if .Values.registry.registry.resources }}
          {{- toYaml .Values.registry.registry.resources | nindent 12 }}
          {{- else }}
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
          {{- end }}
        {{- if not (empty .Values.containerSecurityContext) }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 12 }}
        {{- end }}
        envFrom:
        - secretRef:
            name: "{{ template "harbor.registry" . }}"
        {{- if .Values.persistence.imageChartStorage.s3.existingSecret }}
        - secretRef:
            name: {{ .Values.persistence.imageChartStorage.s3.existingSecret }}
        {{- end }}
        ports:
        - containerPort: {{ template "harbor.registry.containerPort" . }}
        {{- if .Values.metrics.enabled }}
        - containerPort: {{ .Values.metrics.registry.port | default 5001 }}
        {{- end }}
        volumeMounts:
        - name: registry-data
          mountPath: {{ .Values.persistence.imageChartStorage.filesystem.rootdirectory }}
          subPath: {{ .Values.persistence.persistentVolumeClaim.registry.subPath }}
        - name: registry-htpasswd
          mountPath: /etc/registry/passwd
          subPath: passwd
        - name: registry-config
          mountPath: /etc/registry/config.yml
          subPath: config.yml
        {{- if .Values.internalTLS.enabled }}
        - name: registry-internal-certs
          mountPath: /etc/harbor/ssl/registry
        {{- end }}
        {{- if .Values.persistence.imageChartStorage.s3.existingSecret }}
        - name: gcs-key
          mountPath: /etc/registry/gcs-key.json
          subPath: gcs-key.json
        {{- end }}
        {{- if .Values.registry.middleware.enabled }}
        {{- if eq .Values.registry.middleware.type "cloudFront" }}
        - name: cloudfront-key
          mountPath: /etc/registry/pk.pem
          subPath: pk.pem
        {{- end }}
        {{- end }}
      - name: registryctl
        image: {{ .Values.registry.controller.image.repository }}:{{ .Values.registry.controller.image.tag }}
        imagePullPolicy: {{ .Values.registry.controller.image.pullPolicy | default "Always" }}
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          {{- if .Values.registry.controller.resources }}
          {{- toYaml .Values.registry.controller.resources | nindent 10 }}
          {{- else }}
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
          {{- end }}
        {{- if not (empty .Values.containerSecurityContext) }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        {{- end }}
        envFrom:
        - secretRef:
            name: "{{ template "harbor.registry" . }}"
        {{- if .Values.persistence.imageChartStorage.s3.existingSecret }}
        - secretRef:
            name: {{ .Values.persistence.imageChartStorage.s3.existingSecret }}
        {{- end }}
        env:
        {{- if .Values.registry.existingSecret }}
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.registry.existingSecret }}
              key: {{ .Values.registry.existingSecretKey }}
        {{- end }}
        ports:
        - containerPort: {{ template "harbor.registryctl.containerPort" . }}
        volumeMounts:
        - name: registry-data
          mountPath: {{ .Values.persistence.imageChartStorage.filesystem.rootdirectory }}
          subPath: {{ .Values.persistence.persistentVolumeClaim.registry.subPath }}
        - name: registry-config
          mountPath: /etc/registry/config.yml
          subPath: config.yml
        {{- if .Values.internalTLS.enabled }}
        - name: registry-internal-certs
          mountPath: /etc/harbor/ssl/registry
        {{- end }}
      volumes:
      - name: registry-htpasswd
        secret:
          {{- if not .Values.registry.credentials.existingSecret }}
          secretName: {{ template "harbor.registry" . }}-htpasswd
          {{- else }}
          secretName: {{ .Values.registry.credentials.existingSecret }}
          {{- end }}
          items:
            - key: REGISTRY_HTPASSWD
              path: passwd
      - name: registry-config
        configMap:
          name: "{{ template "harbor.registry" . }}"
      - name: registry-data
        {{- if and .Values.persistence.enabled (eq .Values.persistence.imageChartStorage.type "filesystem") }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.persistentVolumeClaim.registry.existingClaim | default (include "harbor.registry" .) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- if .Values.internalTLS.enabled }}
      - name: registry-internal-certs
        secret:
          secretName: {{ template "harbor.internalTLS.registry.secretName" . }}
      {{- end }}
      {{- if and (and .Values.persistence.enabled (eq .Values.persistence.imageChartStorage.type "gcs")) (not .Values.persistence.imageChartStorage.gcs.useWorkloadIdentity ) }}
      - name: gcs-key
        secret:
          secretName: {{ .Values.persistence.imageChartStorage.gcs.existingSecret }}
          items:
            - key: GCS_KEY_DATA
              path: gcs-key.json
      {{- end }}
      {{- if .Values.persistence.imageChartStorage.caBundleSecretName }}
      - name: storage-service-ca
        secret:
          secretName: {{ .Values.persistence.imageChartStorage.caBundleSecretName }}
      {{- end }}
