{{- if .Values.trivy.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: harbor-trivy-network-policy
  namespace: {{ .Release.Namespace | default "harbor" }}
  labels:
    app.kubernetes.io/name: {{ include "harbor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: trivy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: trivy
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress

  # Default deny all other traffic
  ingress:
  - from: []
    ports: []
  
  egress:
  - to: []
    ports: []
  
  # Ingress Rules (Who can connect to Trivy)
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: core
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - port: 8080
      protocol: TCP
  
  # Egress Rules (Where Trivy can connect)
  egress:
  # Allow connections to Harbor Redis
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: redis
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - port: 6379
      protocol: TCP
  
  # Allow connections to Harbor Database
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: database
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - port: 5432
      protocol: TCP
  
  # Allow DNS resolution (critical for service discovery)
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  
  # Allow outbound to external registries for vulnerability DB updates
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - {{ .Values.clusterInternalCIDR | default "10.0.0.0/8" }}
    ports:
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
  
  # Allow connectivity to Kubernetes API (for security contexts)
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          component: kube-apiserver
    ports:
    - port: 6443
      protocol: TCP
{{- end }}
