{{- if .Values.jobservice.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-jobservice
  namespace: harbor
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: jobservice
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: core
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: registry
    ports:
    - protocol: TCP
      port: 5000
{{- end }}
